name: 'Statsig Publish SDK Action'
description: 'Pushes releases from private to public SDK repositories'
author: 'Statsig'

inputs:
  npm-token:
    description: 'The NPM Access Token'

  pypi-token:
    description: 'The PyPI Access Token'

  pypi-beta-token:
    description: 'The PyPI Access Token For Beta Releases'

runs:
  using: 'composite'
  steps:
    - name: Setup Python
      if: ${{ inputs.pypi-token != '' || inputs.pypi-beta-token != '' }}
      uses: statsig-io/statsig-publish-sdk-action/python@main

    - name: Is Beta
      shell: bash
      run: echo ${{ !!github.event.release.prerelease }}

    - name: Run Core
      if: contains(fromJson('["push", "pull_request", "release"]'), github.event_name)
      uses: statsig-io/statsig-publish-sdk-action/core@main
      with:
        gh-token: ${{ secrets.KONG_FINE_GRAINED_REPO_PAT }}
        kong-app-private-key: ${{ secrets.KONG_GH_APP_PRIVATE_KEY }}
        npm-token: ${{ inputs.npm-token }}
        pypi-token: ${{ inputs.pypi-token }}
        pypi-beta-token: ${{ inputs.pypi-beta-token }}
        is-beta: ${{ !!github.event.release.prerelease }}
