name: "Statsig Publish SDK Action"
description: "Pushes releases from private to public SDK repositories"
author: "Statsig"

inputs:
  gh-sync-token:
    description: "The Github Token that has access to both Public and Private repos"
    required: true

  npm-token:
    description: "The NPM Access Token"

  pypi-token:
    description: "The PyPI Access Token"

  pypi-beta-token:
    description: "The PyPI Access Token For Beta Releases"

runs:
  using: "composite"
  steps:
    - name: Setup Python
      if: ${{ inputs.pypi-token != '' || inputs.pypi-beta-token != '' }}
      uses: statsig-io/statsig-publish-sdk-action/python@main

    - name: Is Beta
      shell: bash
      run: echo ${{ !!github.event.release.prerelease }}

    - name: Run Core
      if: contains(fromJson('["push", "pull_request", "release"]'), github.event_name)
      uses: statsig-io/statsig-publish-sdk-action/core@main
      with:
        gh-sync-token: ${{ inputs.gh-sync-token }}
        gh-workflow-token: ${{ github.token }}
        npm-token: ${{ inputs.npm-token }}
        pypi-token: ${{ inputs.pypi-token }}
        pypi-beta-token: ${{ inputs.pypi-beta-token }}
        is-beta: ${{ !!github.event.release.prerelease }}
