name: "Statsig Publish SDK Action"
description: "Pushes releases from private to public SDK repositories"
author: "Statsig"

inputs:
  gh-token:
    description: "The Github Token"
    required: true

  npm-token:
    description: "The NPM Access Token"

  pypi-token:
    description: "The PyPI Access Token"

  pypi-draft-token:
    description: "The PyPI Access Token For Draft Releases"

runs:
  using: "composite"
  steps:
    - name: Setup Python
      if: ${{ inputs.pypi-token != '' || inputs.pypi-draft-token != '' }}
      uses: statsig-io/statsig-publish-sdk-action/python@main

    - name: Is Draft
      shell: bash
      run: echo ${{ github.event.release.draft }}

    - name: Run Core
      if: contains(fromJson('["push", "pull_request", "release"]'), github.event_name)
      uses: statsig-io/statsig-publish-sdk-action/core@main
      with:
        gh-token: ${{ inputs.gh-token }}
        npm-token: ${{ inputs.npm-token }}
        pypi-token: ${{ inputs.pypi-token }}
        pypi-draft-token: ${{ inputs.pypi-draft-token }}
        is-draft: ${{ inputs.is-draft }}
