name: 'Statsig Publish SDK Action'
description: 'Pushes releases from private to public SDK repositories'
author: 'Statsig'

inputs:
  gh-token:
    description: 'The Github Token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Publish
      uses: './action-internal'
      with:
        gh-token: ${{ inputs.gh-token }}

branding:
  icon: 'star'
  color: 'blue'
