name: 'Statsig Publish SDK Action'
description: 'Pushes releases from private to public SDK repositories'
author: 'Statsig'

inputs:
  gh-sync-token:
    description: 'The Github Token that has access to both Public and Private repos'
    required: true

  gh-workflow-token:
    description: 'The Github Token for this workflow (See https://docs.github.com/en/actions/security-guides/automatic-token-authentication)'
    required: true

  npm-token:
    description: 'The NPM Access Token'

  pypi-token:
    description: 'The PyPI Access Token'

  pypi-beta-token:
    description: 'The PyPI Access Token For Beta Releases'

  is-beta:
    description: 'Beta Release?'
    default: false

runs:
  using: 'node16'
  main: 'dist/index.js'

branding:
  icon: 'star'
  color: 'blue'
