name: "Statsig Publish SDK Action"
description: "Pushes releases from private to public SDK repositories"
author: "Statsig"

runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install Python Tools
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
